"""Initial migration

Revision ID: 09dd371c105a
Revises: 
Create Date: 2026-01-17 20:12:08.191346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09dd371c105a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('opponent_name', sa.String(), nullable=False),
    sa.Column('blue_side', sa.Boolean(), nullable=False),
    sa.Column('picks', sa.JSON(), nullable=False),
    sa.Column('bans', sa.JSON(), nullable=False),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drafts_id'), 'drafts', ['id'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('summoner_name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_id'), 'players', ['id'], unique=False)
    op.create_index(op.f('ix_players_summoner_name'), 'players', ['summoner_name'], unique=True)
    op.create_table('player_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('author_role', sa.String(), nullable=False),
    sa.Column('note_type', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_notes_id'), 'player_notes', ['id'], unique=False)
    op.create_table('riot_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('puuid', sa.String(), nullable=False),
    sa.Column('summoner_name', sa.String(), nullable=False),
    sa.Column('tag_line', sa.String(), nullable=False),
    sa.Column('is_main', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_riot_accounts_id'), 'riot_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_riot_accounts_puuid'), 'riot_accounts', ['puuid'], unique=True)
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('riot_account_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.String(), nullable=False),
    sa.Column('game_type', sa.String(), nullable=False),
    sa.Column('champion_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.Column('game_duration', sa.Integer(), nullable=False),
    sa.Column('game_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['riot_account_id'], ['riot_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_id'), 'games', ['id'], unique=False)
    op.create_index(op.f('ix_games_match_id'), 'games', ['match_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_games_match_id'), table_name='games')
    op.drop_index(op.f('ix_games_id'), table_name='games')
    op.drop_table('games')
    op.drop_index(op.f('ix_riot_accounts_puuid'), table_name='riot_accounts')
    op.drop_index(op.f('ix_riot_accounts_id'), table_name='riot_accounts')
    op.drop_table('riot_accounts')
    op.drop_index(op.f('ix_player_notes_id'), table_name='player_notes')
    op.drop_table('player_notes')
    op.drop_index(op.f('ix_players_summoner_name'), table_name='players')
    op.drop_index(op.f('ix_players_id'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_drafts_id'), table_name='drafts')
    op.drop_table('drafts')
    # ### end Alembic commands ###
