"""add rank tracking to riot_accounts

Revision ID: 4a34cb89de4c
Revises: 61178ce193b7
Create Date: 2026-01-17 22:04:15.878698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a34cb89de4c'
down_revision: Union[str, None] = '61178ce193b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('riot_accounts', sa.Column('rank_tier', sa.String(), nullable=True))
    op.add_column('riot_accounts', sa.Column('rank_division', sa.String(), nullable=True))
    op.add_column('riot_accounts', sa.Column('lp', sa.Integer(), nullable=True))
    op.add_column('riot_accounts', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('riot_accounts', 'updated_at')
    op.drop_column('riot_accounts', 'lp')
    op.drop_column('riot_accounts', 'rank_division')
    op.drop_column('riot_accounts', 'rank_tier')
    # ### end Alembic commands ###
