"""add pentakill tracking to games

Revision ID: fdfb0ddf8b32
Revises: 4a34cb89de4c
Create Date: 2026-01-18 01:15:49.559421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdfb0ddf8b32'
down_revision: Union[str, None] = '4a34cb89de4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('is_pentakill', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'is_pentakill')
    # ### end Alembic commands ###
